// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wthxfynxlcmafssqlplk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0aHhmeW54bGNtYWZzc3FscGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzIwMjcsImV4cCI6MjA2NDMwODAyN30.mW9nhW-zh4Ac3hOTb7KA9AxzmuGMYsHoMDBJUmwcFi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);